version: '3.8'

services:
  backend:
    build: ./backend
    container_name: social-backend
    ports:
      - "8081:8081"
    volumes:
      - ./backend/imageUpload:/app/imageUpload  # Persist uploaded images
    networks:
      - socialnet

  frontend:
    build: ./frontend
    container_name: social-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - socialnet

networks:
  socialnet:
    driver: bridge

